"""add gernid to movie table

Revision ID: 327c812fff15
Revises: de054dd7690a
Create Date: 2026-02-28 09:11:55.448579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327c812fff15'
down_revision: Union[str, Sequence[str], None] = 'de054dd7690a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('gerne_ids', sa.ARRAY(sa.Integer()), nullable=False, server_default="{}"))
    op.create_index(op.f('ix_movies_gerne_ids'), 'movies', ['gerne_ids'], unique=False)
    op.create_index(op.f('ix_rating_rating_id'), 'rating', ['rating_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_rating_id'), table_name='rating')
    op.drop_index(op.f('ix_movies_gerne_ids'), table_name='movies')
    op.drop_column('movies', 'gerne_ids')
    # ### end Alembic commands ###
