"""movie search table

Revision ID: 57ba3175e6e7
Revises: 887a1a7ac529
Create Date: 2026-02-26 01:36:15.446029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ba3175e6e7'
down_revision: Union[str, Sequence[str], None] = '887a1a7ac529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('saved_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'saved_at')
    # ### end Alembic commands ###
