"""movie search table

Revision ID: 887a1a7ac529
Revises: 62168199f275
Create Date: 2026-02-25 23:10:10.815616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887a1a7ac529'
down_revision: Union[str, Sequence[str], None] = '62168199f275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('movie_title', sa.String(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_index(op.f('ix_movies_movie_id'), 'movies', ['movie_id'], unique=True)
    op.create_index(op.f('ix_movies_movie_title'), 'movies', ['movie_title'], unique=False)
    op.create_index(op.f('ix_movies_poster_path'), 'movies', ['poster_path'], unique=False)
    op.create_index(op.f('ix_movies_release_date'), 'movies', ['release_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_release_date'), table_name='movies')
    op.drop_index(op.f('ix_movies_poster_path'), table_name='movies')
    op.drop_index(op.f('ix_movies_movie_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_movie_id'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
