"""added default value to created-at and updated-at fields

Revision ID: 8ae34ddbbae7
Revises: 8f4bd7bb4376
Create Date: 2026-03-02 15:07:42.449226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae34ddbbae7'
down_revision: Union[str, Sequence[str], None] = '8f4bd7bb4376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
