"""add genre_id to movie table

Revision ID: 8ae58c754bc1
Revises: 327c812fff15
Create Date: 2026-02-28 09:19:38.492418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ae58c754bc1'
down_revision: Union[str, Sequence[str], None] = '327c812fff15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('genre_ids', sa.ARRAY(sa.Integer()), nullable=False, server_default="{}"))
    op.drop_index(op.f('ix_movies_gerne_ids'), table_name='movies')
    op.create_index(op.f('ix_movies_genre_ids'), 'movies', ['genre_ids'], unique=False)
    op.drop_column('movies', 'gerne_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('gerne_ids', postgresql.ARRAY(sa.INTEGER()), server_default=sa.text("'{}'::integer[]"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_movies_genre_ids'), table_name='movies')
    op.create_index(op.f('ix_movies_gerne_ids'), 'movies', ['gerne_ids'], unique=False)
    op.drop_column('movies', 'genre_ids')
    # ### end Alembic commands ###
