"""watchlist

Revision ID: c0e66d05d03f
Revises: 57ba3175e6e7
Create Date: 2026-02-26 23:42:16.583055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e66d05d03f'
down_revision: Union[str, Sequence[str], None] = '57ba3175e6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('watchlist_id')
    )
    op.create_index(op.f('ix_watchlist_movie_id'), 'watchlist', ['movie_id'], unique=True)
    op.create_index(op.f('ix_watchlist_owner_id'), 'watchlist', ['owner_id'], unique=False)
    op.create_index(op.f('ix_watchlist_watchlist_id'), 'watchlist', ['watchlist_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_watchlist_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_owner_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_movie_id'), table_name='watchlist')
    op.drop_table('watchlist')
    # ### end Alembic commands ###
