"""rating

Revision ID: de054dd7690a
Revises: c0e66d05d03f
Create Date: 2026-02-27 02:52:30.759856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de054dd7690a'
down_revision: Union[str, Sequence[str], None] = 'c0e66d05d03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('rating_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_index(op.f('ix_rating_movie_id'), 'rating', ['movie_id'], unique=True)
    op.create_index(op.f('ix_rating_owner_id'), 'rating', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_owner_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_movie_id'), table_name='rating')
    op.drop_table('rating')
    # ### end Alembic commands ###
