"""create_users

Revision ID: fd11b5dd6dff
Revises: 
Create Date: 2026-02-24 08:01:10.143905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd11b5dd6dff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_index(op.f('ix_user_account_first_name'), 'user_account', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_account_last_name'), 'user_account', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_account_user_id'), 'user_account', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_account_username'), 'user_account', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_username'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_user_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_last_name'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_first_name'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
